require:
  - rubocop-performance
  - rubocop-rake

AllCops:
  NewCops: enable
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'

Metrics/MethodLength:
  Max: 14

Metrics/ClassLength:
  Max: 100

Metrics/BlockLength:
  Max: 33

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/PerceivedComplexity:
  Max: 12

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Naming/RescuedExceptionsVariableName:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: true
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space
  SpaceBeforeBlockParameters: true

Layout/SpaceBeforeBlockBraces:
  Enabled: true
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: space

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: compact
  EnforcedStyleForEmptyBraces: no_space

Layout/EmptyLinesAroundClassBody:
  Enabled: true
  EnforcedStyle: empty_lines_except_namespace

Layout/EmptyLinesAroundModuleBody:
  Enabled: true
  EnforcedStyle: empty_lines_except_namespace

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Layout/HashAlignment:
  Enabled: true
  EnforcedLastArgumentHashStyle: always_ignore

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/RaiseArgs:
  EnforcedStyle: compact

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/YodaCondition:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/RegexpLiteral:
  Enabled: true
  EnforcedStyle: slashes
  AllowInnerSlashes: false

Style/FormatStringToken:
  Enabled: false

Style/SlicingWithRange:
  Enabled: true

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Style/Documentation:
  Enabled: false

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Lint/Loop:
  Enabled: false

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/SafeNavigation:
  Enabled: true
  AllowedMethods:
    - present?
    - blank?
    - presence

Style/RedundantFetchBlock:
  Enabled: true

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Naming/PredicateName:
  Exclude:
    - 'spec/**/*'

Style/NumericPredicate:
  Exclude:
    - 'spec/**/*'

Naming/BlockForwarding:
  Enabled: true
  EnforcedStyle: explicit

Style/HashSyntax:
  Enabled: true
  EnforcedStyle: ruby19
  EnforcedShorthandSyntax: either
