compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - linux
    - darwin

yarnPath: .yarn/releases/yarn-4.12.0.cjs
